version: "3.8"

services:
    app:
        image: node:16
        volumes:
            - type: bind
              source: ./
              target: /app
        working_dir: /app
        ports:
            - "5173:5173"
        tty: true
